Create hormone-levels-during-normal-puberty-in-cisgender-girls
project-trans/transfeminine-science pull request #7
Opened 2023-02-07 04:42 UTC by Aquaticat

有一些不清楚如何翻译的地方，请提建议：

1. trackHash 是什么？

2. keywords 应写哪些？

3. [wiki-aaaaaaaa] 这个写法是什么？

应该还有很多其它翻译得不对或者不准确的地方。请指导。

Signed-off-by: Aquaticat <an@aquati.cat>

2023-02-08 03:16 UTC, Bersella-AI commented
1. `trackHash` 和 `[wiki-1a2b3c4d]` 等标识需配合一个追踪 TFsci 原站文章更新的 repo 来使用，但该 repo 仅对 MtF.wiki 内部可见。`trackHash` 可以留空。
2. `keywords` 意为“关键词”，需要填上简要概括文章内容的几个词语。可以留空。

2023-02-09 07:27 UTC, septs commented on content/articles/hormone-levels-female-puberty.md
> +  - 孕激素
```suggestion
  - 孕激素
```

2023-02-09 07:28 UTC, septs commented on content/articles/hormone-levels-female-puberty.md
> +  - Aquaticat
https://github.com/mtf-wiki/transfeminine-science/blob/main/content/about.md?plain=1

在 about 添加关于自己的描述

2023-02-09 07:52 UTC, Aquaticat commented on content/articles/hormone-levels-female-puberty.md
> +  - Aquaticat
已添加。

2023-02-09 12:53 UTC, Bersella-AI requested changes

2023-02-09 12:53 UTC, Bersella-AI commented on content/articles/hormone-levels-female-puberty.md
> +| 14–17 years | 	≤11.9     |
还是有遗漏的地方……

2023-02-09 12:53 UTC, Bersella-AI commented on content/articles/hormone-levels-female-puberty.md
> +      在不同的Tanner 乳房发育阶段的雌酮水平。
这行字其实是原作者的注解，不是被引用的部分。只有引用文献要保留原文。

2023-02-09 12:53 UTC, Bersella-AI commented on content/articles/hormone-levels-female-puberty.md
> +  以气相色谱-串联质谱法分别对不同性别和是否处于发育期的人的血清雄烯二酮、睾酮、双氢睾酮、雌酮和雌二醇水平进行高灵敏度的定量分析。
第 163 行似乎是早期的翻译，除去。

2023-02-09 12:53 UTC, Bersella-AI commented on content/articles/hormone-levels-female-puberty.md
> +| 生命阶段或年龄         | 参考范围 (pg/mL)	 | 参考范围 (pg/mL) |
没必要完全遵循原站的格式和排版。可以这么处理：
```
| 生命阶段或年龄 | 雌二醇参考范围 | 雌酮参考范围 |
|-|-|-|
| …… | …… | …… |
```

2023-02-09 12:53 UTC, Bersella-AI commented on content/articles/hormone-levels-female-puberty.md
> +  发育期前女孩的荷尔蒙变化
前缀 peri-\* 是“某个时期当中”的意思。“某个时期前”用 pre-\* ；“某个时期后”用 post-\* 。

2023-02-09 12:53 UTC, Bersella-AI commented on content/articles/hormone-levels-female-puberty.md
> +少年男子（1 - 10 岁和发育期）的孕酮水平 <0.10–1.1 ng/mL。成年男子的孕酮水平 0.13–0.97 ng/mL。
1 ~ 10 岁到发育期，可统称“男孩”。现代中文一般不用“少年男子”称呼，而用“少年”。

2023-02-09 13:02 UTC, Aquaticat commented on content/articles/hormone-levels-female-puberty.md
> +  以气相色谱-串联质谱法分别对不同性别和是否处于发育期的人的血清雄烯二酮、睾酮、双氢睾酮、雌酮和雌二醇水平进行高灵敏度的定量分析。
此处既要表达”对不同人群定下不同的各激素水平参考范围“，又要表达“以...法，对各激素水平进行高灵敏度的定量分析”。所以我当时认为写成两句话更通顺。

2023-02-09 13:03 UTC, Aquaticat commented on content/articles/hormone-levels-female-puberty.md
> +      在不同的Tanner 乳房发育阶段的雌酮水平。
好的。

2023-02-09 13:03 UTC, Aquaticat commented on content/articles/hormone-levels-female-puberty.md
> +| 生命阶段或年龄         | 参考范围 (pg/mL)	 | 参考范围 (pg/mL) |
好的。

2023-02-09 13:04 UTC, Aquaticat commented on content/articles/hormone-levels-female-puberty.md
> +  发育期前女孩的荷尔蒙变化
好的。

2023-02-09 13:05 UTC, Aquaticat commented on content/articles/hormone-levels-female-puberty.md
> +| 14–17 years | 	≤11.9     |
好的。

2023-02-09 13:06 UTC, Aquaticat commented on content/articles/hormone-levels-female-puberty.md
> +少年男子（1 - 10 岁和发育期）的孕酮水平 <0.10–1.1 ng/mL。成年男子的孕酮水平 0.13–0.97 ng/mL。
此处是遗漏。已修改。

2023-02-09 14:29 UTC, septs commented
@Bersella-AI 可以考虑以 track 的底稿为基础吧以翻译的文本替换其中，以提高效率

2023-02-11 15:50 UTC, Bersella-AI requested changes

2023-02-11 15:50 UTC, Bersella-AI commented on content/articles/hormone-levels-female-puberty.md
> +| Tanner 阶段 5 | 76-81 | 41         | 34-170    | 61         | 29-105    |
表四数据与原文不符，请更正。

2023-02-11 15:50 UTC, Bersella-AI commented on content/articles/hormone-levels-female-puberty.md
> +  以气相色谱-串联质谱法分别对不同性别和是否处于发育期的人的血清雄烯二酮、睾酮、双氢睾酮、雌酮和雌二醇水平进行高灵敏度的定量分析。
但需注意，译文*只需* 保留一个版本。给读者*做选择* 是很不负责任的，会造成严重困惑。此处 `-specific` 后缀没有“按照……定下”这样的**主观意识**，只是用于按照**客观事实**区分人群类型。

2023-02-11 15:50 UTC, Bersella-AI commented on content/articles/hormone-levels-female-puberty.md
> +    * 在不同的 Tanner 乳房发育阶段的雌酮水平。
需要重新翻译：原文是指（上述论文）有这样的数据，而且 estrone sulfate（硫酸雌酮）不是雌酮，是雌酮的一种代谢物。

2023-02-11 15:50 UTC, Bersella-AI commented on content/articles/hormone-levels-female-puberty.md
> +  探讨年龄，性别，发育期，和口服式避孕药对以 LC-MS/MS 测得的九种类固醇荷尔蒙的参考范围的影响。
这样的语序有点令人不明所以。“以 LC-MS/MS 测定”可以作为附注，加上括号置于句末。此外，“荷尔蒙”是较过时的说法，用“激素”即可。
我对此标题的释义是：“一生里人体九种类固醇激素的参考范围（以 LC-MS/MS 测定），以及年龄、性别、青春期和口服避孕药对其的影响。”

2023-02-11 15:50 UTC, Bersella-AI commented on content/articles/hormone-levels-female-puberty.md
> +Fisher, D. A., Quest Diagnostics, Nichols Institute (2007). 奎斯特诊断公司操作手册：内分泌学测试选择与诠释，第四版。[[PDF](http://docplayer.net/86293048-The-quest-diagnostics-manual-endocrinology-test-selection-and-interpretati
这两行应合并。

2023-02-11 15:50 UTC, Bersella-AI commented on content/articles/hormone-levels-female-puberty.md
> +5 - 17 岁青少年男孩的孕酮水平 ≤0.3 ng/mL。成年男性的孕酮水平 ≤1.2 ng/mL。
二者的数据弄反了。

2023-02-11 15:50 UTC, Bersella-AI commented on content/articles/hormone-levels-female-puberty.md
> +| 生命阶段         | 年龄         | 平均值 (ng/dL) | 范围 (ng/dL) |
表八至表十一的“年龄”应加上单位“岁”。

2023-02-11 15:50 UTC, Bersella-AI commented on content/articles/hormone-levels-female-puberty.md
> +| 成人停经前期	      | >18.0	     | ?           | 	28–230    |
表十这行的年龄并非“大于 18”，而是 18-40。

2023-02-11 15:50 UTC, Bersella-AI commented on content/articles/hormone-levels-female-puberty.md
> +| 成人停经前期	      | >18.0	     | ?           | 	17–372    |
表十一这行的年龄并非“大于 18”，而是 18-50。

2023-02-11 15:50 UTC, Bersella-AI commented on content/articles/hormone-levels-female-puberty.md
> +  一种新型的血清睾丸激素串联质谱分析法的性能和特点。
对同一名词、术语的翻译应*至少* 在同一文章内一致。不能这边用“睾丸激素”，那边用“睾酮”。

2023-02-12 00:12 UTC, Aquaticat commented on content/articles/hormone-levels-female-puberty.md
> +| Tanner 阶段 5 | 76-81 | 41         | 34-170    | 61         | 29-105    |
好的

2023-02-12 00:16 UTC, Aquaticat commented on content/articles/hormone-levels-female-puberty.md
> +  以气相色谱-串联质谱法分别对不同性别和是否处于发育期的人的血清雄烯二酮、睾酮、双氢睾酮、雌酮和雌二醇水平进行高灵敏度的定量分析。
好的。

2023-02-12 00:18 UTC, Aquaticat commented on content/articles/hormone-levels-female-puberty.md
> +    * 在不同的 Tanner 乳房发育阶段的雌酮水平。
好的。

2023-02-12 00:20 UTC, Aquaticat commented on content/articles/hormone-levels-female-puberty.md
> +  探讨年龄，性别，发育期，和口服式避孕药对以 LC-MS/MS 测得的九种类固醇荷尔蒙的参考范围的影响。
好的。还是觉得不通顺，不过也想不到更好的表达方式了。

2023-02-12 00:21 UTC, Aquaticat commented on content/articles/hormone-levels-female-puberty.md
> +Fisher, D. A., Quest Diagnostics, Nichols Institute (2007). 奎斯特诊断公司操作手册：内分泌学测试选择与诠释，第四版。[[PDF](http://docplayer.net/86293048-The-quest-diagnostics-manual-endocrinology-test-selection-and-interpretati
好的

2023-02-12 00:23 UTC, Aquaticat commented on content/articles/hormone-levels-female-puberty.md
> +5 - 17 岁青少年男孩的孕酮水平 ≤0.3 ng/mL。成年男性的孕酮水平 ≤1.2 ng/mL。
好的

2023-02-12 00:24 UTC, Aquaticat commented on content/articles/hormone-levels-female-puberty.md
> +| 生命阶段         | 年龄         | 平均值 (ng/dL) | 范围 (ng/dL) |
好的

2023-02-12 00:27 UTC, Aquaticat commented on content/articles/hormone-levels-female-puberty.md
> +| 成人停经前期	      | >18.0	     | ?           | 	28–230    |
好的

2023-02-12 00:27 UTC, Aquaticat commented on content/articles/hormone-levels-female-puberty.md
> +| 成人停经前期	      | >18.0	     | ?           | 	17–372    |
好的

2023-02-12 00:27 UTC, Aquaticat commented on content/articles/hormone-levels-female-puberty.md
> +  一种新型的血清睾丸激素串联质谱分析法的性能和特点。
好的

2023-02-17 14:50 UTC, Bersella-AI approved these changes
校对得差不多了。为了和原站文章、以及本站译文的高标准相契合，这篇译文前前后后一共指出了超过 50 项问题，我花的时间相当于**把全文核对五六遍**；但这种工作是值得的：**这会为今后其他有意参与的伙伴提供一个规范化、高标准的指引**。我会择机以此 PR 为例发表《贡献指南》。
另外提醒所有意欲参与的伙伴：各位的贡献质量如何、是否能够节约我的时间和精力，都不重要——事实上我对译文的基本要求只有“**如实传达**”（项目主页原文）；重要的是**这对你自己而言是否值得去付出时间和精力**。光有热爱是不够的，还需各位斟酌一二。

2023-02-17 14:55 UTC, merged