Refine Hormone levels female puberty
project-trans/transfeminine-science pull request #8
Opened 2023-02-20 10:02 UTC by septs

2023-02-20 10:13 UTC, septs commented
CC @Aquaticat

2023-02-20 10:50 UTC, Bersella-AI requested changes

2023-02-20 10:50 UTC, Bersella-AI commented on content/articles/hormone-levels-female-puberty.md
> +Frederiksen, H., Johannsen, T. H., Andersen, S. E., Albrethsen, J., Landersoe, S. K., Petersen, J. H., … & Main, K. M. (2020). 不同性别人群从出生到晚年的雌激素水平和参考范围变化，以 LC-MS/MS 测定. *The Journal of Clinical Endocr
我个人对正文内（非“参考文献”一节）插入的引用文献的表述是这样：
```markdown
- 原作者. (年份). \
  原标题. (标题翻译)\
  所在期刊, 期数, 页数. [DOI:...]
```
也就是说，原标题会保留，而不是移除。另外作者、标题、期刊分三行来显示。

2023-02-20 10:55 UTC, septs commented on content/articles/hormone-levels-female-puberty.md
> +Frederiksen, H., Johannsen, T. H., Andersen, S. E., Albrethsen, J., Landersoe, S. K., Petersen, J. H., … & Main, K. M. (2020). 不同性别人群从出生到晚年的雌激素水平和参考范围变化，以 LC-MS/MS 测定. *The Journal of Clinical Endocr
以本 cite 为例

原文：

```
Frederiksen, H., Johannsen, T. H., Andersen, S. E., Albrethsen, J., Landersoe, S. K., Petersen, J. H., … & Main, K. M. (2020). Sex-specific estrogen levels and reference intervals from infancy to late adulthood determined by LC-MS/MS. *The Journal of Clinical Endocrinology & Metabolism*, *105*(3), 754–768. \[DOI:[10.1210/clinem/dgz196][doi-49b32caa]]
```

修改后：

```
Frederiksen, H., Johannsen, T. H., Andersen, S. E., Albrethsen, J., Landersoe, S. K., Petersen, J. H., … & Main, K. M. (2020). \
Sex-specific estrogen levels and reference intervals from infancy to late adulthood determined by LC-MS/MS. \
不同性别人群从出生到晚年的雌激素水平和参考范围变化，以 LC-MS/MS 测定. \
*The Journal of Clinical Endocrinology & Metabolism*, *105*(3), 754–768. \[DOI:[10.1210/clinem/dgz196][doi-49b32caa]]
```

如果理解无误则按本规则（逻辑）处理

2023-02-20 12:09 UTC, Bersella-AI commented on content/articles/hormone-levels-female-puberty.md
> +Frederiksen, H., Johannsen, T. H., Andersen, S. E., Albrethsen, J., Landersoe, S. K., Petersen, J. H., … & Main, K. M. (2020). 不同性别人群从出生到晚年的雌激素水平和参考范围变化，以 LC-MS/MS 测定. *The Journal of Clinical Endocr
译名和原标题处于同一行，且加括号。即：
```markdown
- Frederiksen, H., Johannsen, T. H., Andersen, S. E., Albrethsen, J., Landersoe, S. K., Petersen, J. H., … & Main, K. M. (2020).\
  Sex-specific estrogen levels and reference intervals from infancy to late adulthood determined by LC-MS/MS. （不同性别人群从出生到晚年的雌激素水平和参考范围变化，以 LC-MS/MS 测定）\
  *The Journal of Clinical Endocrinology & Metabolism*, *105*(3), 754–768. \[DOI:[10.1210/clinem/dgz196][doi-49b32caa]]
```

2023-02-20 14:31 UTC, Bersella-AI approved these changes
看样子没什么问题了。

2023-02-20 14:34 UTC, Bersella-AI commented
如无进一步改动，24小时后合并。

2023-02-21 14:33 UTC, Bersella-AI approved these changes

2023-02-21 14:35 UTC, merged